url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Mapzy"


plugins:
  - jekyll-postcss
  - jekyll-include-cache  

exclude:
  - node_modules
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - purgecss.config.js
  - package.json
  - README.md
  - LICENSE
  - assets/css/tailwind.scss

keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map